export const franchiseCities = [
  "Ajax",
  "Aurora",
  "Barrie",
  "Belleville",
  "Bowmanville",
  "Bradford",
  "Brampton",
  "Brant",
  "Brantford",
  "Brockville",
  "Burlington",
  "Caledon",
  "Calgary",
  "Cambridge",
  "Clarence-Rockland",
  "Clarington",
  "Cornwall",
  "Courtice",
  "Dryden",
  "East Gwillimbury",
  "Edmonton",
  "Elliot Lake",
  "Etobicoke",
  "Georgetown",
  "Greater Sudbury",
  "Guelph",
  "Haldimand County",
  "Hamilton",
  "Innisfil",
  "Kawartha Lakes",
  "Kenora",
  "Kingston",
  "Kitchener",
  "London",
  "Markham",
  "Milton",
  "Mississauga",
  "Newmarket",
  "Niagara",
  "Niagara Falls",
  "Norfolk County",
  "North Bay",
  "North York",
  "Oakville",
  "Orillia",
  "Oshawa",
  "Ottawa",
  "Owen Sound",
  "Pembroke",
  "Peterborough",
  "Pickering",
  "Port Colborne",
  "Prince Edward County",
  "Quinte West",
  "Richmond Hill",
  "Sarnia",
  "Sault Ste Marie",
  "Scarborough",
  "St Catharines",
  "St Thomas",
  "Stratford",
  "Temiskaming Shores",
  "Thorold",
  "Thunder Bay",
  "Timmins",
  "Toronto",
  "Vaughan",
  "Waterloo",
  "Welland",
  "Whitby",
  "Windsor",
  "Woodstock",
];
